### ISSUE TITLE
this.offlineBarRef not getting 

### ISSUE THREAD

**Issue by mspvirajpatel** [rgabs/react-native-offline-status#1]
this.offlineBarRef not get with ref.

**Comment by rgabs** [comment]
Hey @mspvirajpatel,
Can you post the snippet here?

**Comment by mspvirajpatel** [comment]
my Code : https://gist.github.com/mspvirajpatel/5ab9f341613b63b8e617734cd7c7838e

**Comment by rgabs** [comment]
Hey @mspvirajpatel,
I just checked and it works for me. Looking at your code I think the problem is where you are printing `this.offlineBarRef.state.isConnected`

In the first render, the reference wouldn't have been created and you might get an error saying `Cannot read property state of undefined`. Removing this should fix the issue. If you want to read the current state of the network, then better use NetInfo module from react-native.

**Comment by mspvirajpatel** [comment]
I use this function so i can use this this.offlineBarRef.state.isConnected.
I also check in button click event but its also not working.
if any solution and give your snippet 
Thanks.

**Comment by rgabs** [comment]
The button click handler doesn't work because you are not calling the
function.

Try `onPress={()=> this.offlineBarRef.setState({isConnected: false})}`

On 27-Aug-2017 9:42 AM, "VD" <notifications@github.com> wrote:

I use this function so i can use this this.offlineBarRef.state.isConnected.
I also check in button click event but its also not working.
if any solution and give your snippet
Thanks.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/rgabs/react-native-offline-status/issues/1#issuecomment-325176100>,
or mute the thread
